config/routes.rb
Gamesdb::Application.routes.draw do
  resources :games

  root :to => "games#index"

end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :title, :players, :presence => true
  validates :players, :numericality => {:only_integer => :true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.xml
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @games }
    end
  end

  # GET /games/1
  # GET /games/1.xml
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @game }
    end
  end

  # GET /games/new
  # GET /games/new.xml
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.xml
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to(:games, :notice => "Game '#{@game.title}' was successfully created.") }
        format.xml  { render :xml => @game, :status => :created, :location => @game }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.xml
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to(:games, :notice => "Game '#{@game.title}' was successfully updated.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.xml
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to(games_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :players %><br />
    <%= f.text_field :players %>
  </div>
  <div class="field">
    <%= f.label :system %><br />
    <%= f.text_field :system %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h2>Listing games</h2>

<% flash.each do |key, msg| %>
  <div id="<%= key %>">
    <p><%= msg %><p>
  </div>
<% end %>

<script type='text/javascript'>
  $(document).ready(function()
    {
      $("#myTable").tablesorter();
    }
  );
</script>

<table id="myTable" class="tablesorter">
<thead>
  <tr>
    <th>Title</th>
    <th>Players</th>
    <th>Completed</th>
    <th>Genre</th>
    <th>System</th>
    <th>Location</th>
    <!-- <th></th> -->
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @games.each do |game| %>
  <tr>
    <td><%= game.title %></td>
    <td><%= game.players %></td>
    <td><%= game.completed.to_s.capitalize %></td>
    <td><%= game.genre %></td>
    <td><%= game.system %></td>
    <td><%= game.location %></td>
    <!-- <td><%= link_to 'Show', game %></td> -->
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Delete', game, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @game.title %>
</p>

<p>
  <b>Players:</b>
  <%= @game.players %>
</p>

<p>
  <b>System:</b>
  <%= @game.system %>
</p>

<p>
  <b>Genre:</b>
  <%= @game.genre %>
</p>

<p>
  <b>Location:</b>
  <%= @game.location %>
</p>

<p>
  <b>Completed:</b>
  <%= @game.completed.to_s.capitalize %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamesdb</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
<h1>Peter's Ultimate Game Database</h1>

<%= yield %>

</body>
</html>